
# Example Workflow YAML: ITSM triage (ServiceNow + Slack) — v0.1
apiVersion: workflow.ai-platform/v1
kind: Workflow
metadata:
  name: itsm-triage-servicenow
  version: 0.1.0
spec:
  riskTier: medium
  modelPin:
    provider: openai
    model: gpt-4.1-mini
    allowFallback: false
  triggers:
    - type: webhook
      source: servicenow
      event: incident.created
  steps:
    - id: fetch_incident
      toolAction: servicenow.get_incident
      input:
        instance_id: "{{trigger.instance_id}}"
        incident_sys_id: "{{trigger.sys_id}}"
    - id: summarize_classify
      action: llm.complete
      input:
        system_prompt: "You are an ITSM triage assistant. Never performG: do not execute tools; propose structured triage only."
        user_input: |
          Summarize and classify this incident. Propose assignment group and priority.
          Incident JSON (redacted fields may be missing):
          {{steps.fetch_incident.output}}
      outputSchema:
        type: object
        required: [summary, category, priority, proposed_assignment_group, confidence]
        properties:
          summary: { type: string }
          category: { type: string }
          priority: { type: string }
          proposed_assignment_group: { type: string }
          confidence: { type: number, minimum: 0, maximum: 1 }
    - id: approval
      action: hitl.request
      input:
        channel: slack
        title: "Approve ITSM triage writeback?"
        message: |
          Summary: {{steps.summarize_classify.output.summary}}
          Category: {{steps.summarize_classify.output.category}}
          Priority: {{steps.summarize_classify.output.priority}}
          Proposed assignment: {{steps.summarize_classify.output.proposed_assignment_group}}
          Confidence: {{steps.summarize_classify.output.confidence}}
    - id: writeback_update
      when: "{{steps.approval.decision}} == 'approve'"
      toolAction: servicenow.update_incident_reversible
      input:
        instance_id: "{{trigger.instance_id}}"
        incident_sys_id: "{{trigger.sys_id}}"
        idempotency_key: "{{run.idempotency_key}}"
        fields:
          category: "{{steps.summarize_classify.output.category}}"
          priority: "{{steps.summarize_classify.output.priority}}"
          assignment_group: "{{steps.summarize_classify.output.proposed_assignment_group}}"
    - id: writeback_note
      when: "{{steps.approval.decision}} == 'approve'"
      toolAction: servicenow.add_work_note
      input:
        instance_id: "{{trigger.instance_id}}"
        incident_sys_id: "{{trigger.sys_id}}"
        idempotency_key: "{{run.idempotency_key}}"
        note: "AI triage summary: {{steps.summarize_classify.output.summary}}"
